#!/bin/sh
echo 1 >/proc/sys/net/ipv4/ip_forward
ipchains -A forward -s 10.100.113.106/32 -d ! 10.0.0.0/8 -j MASQ
ipchains -A forward -s 10.100.113.60/32 -d ! 10.0.0.0/8 -j MASQ
ipchains -A forward -s 10.100.113.133/32 -d ! 10.0.0.0/8 -j MASQ

